// Auto-generated by CI in .github/workflows/android-apk.yml.
// Do NOT edit by hand. Local dev fallback values are used when no CI run wrote this file.
export const BUILD_TIME_ISO = '1970-01-01T00:00:00Z';
export const BUILD_COMMIT = 'dev';
